server:
  port: 8080
spring:
  datasource:
    username: root
    password: "0403"
    url: jdbc:mysql://localhost:3306/xjtu
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: xjtu.pojo
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name: log/backend.log
  level:
    root: info
    xjtu: debug
